export const entries_report_columns = [
  {
    name: "product",
    required: true,
    label: "Product",
    align: "left",
    field: (row) => row.product,
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: "parts",
    align: "center",
    label: "Measurement",
    field: "parts",
    sortable: true,
  },
  { name: "units", label: "Unit", field: "units", sortable: true },
  {
    name: "unit_price",
    label: "Unit Price",
    field: "unit_price",
    sortable: true,
  },
  {
    name: "opening_stock",
    label: "Opening Stock",
    field: "opening_stock",
    sortable: true,
  },
  {
    name: "closing_stock",
    label: "Closing Stock",
    field: "closing_stock",
    sortable: true,
  },
  { name: "purchases", label: "Purchases", field: "purchases", sortable: true },
  {
    name: "purchases_cost",
    label: "Purchases Cost",
    field: "purchases_cost",
    sortable: true,
  },
  {
    name: "closing_stock_cost",
    label: "Closing Stock Cost",
    field: "closing_stock_cost",
    sortable: true,
  },
  { name: "usage", label: "Usage", field: "usage", sortable: true },
  {
    name: "usage_cost",
    label: "Usage Cost",
    field: "usage_cost",
    sortable: true,
  },
  {
    name: "system_usage",
    label: "System Usage",
    field: "system_usage",
    sortable: true,
  },
  { name: "user", label: "User", field: "user", sortable: true },
  {
    name: "created_at",
    label: "Created On",
    field: "created_at",
    sortable: true,
  },
];
